database:
  type: "SQLite"
  mysql:
    host: "localhost"
    port: 3306
    database: "merchpunishments"
    username: "root"
    password: ""
  mongodb:
    uri: "mongodb://localhost:27017"
    database: "merchpunishments"

messages:
  prefix: "&e&l[&c&lMerchPunishs&e&l] &f"
  player_banned: "&cYou are banned on this server!\n&cReason: &e%reason%\n&cExpires: &e%expiry%"
  player_muted: "&cYou are muted and cannot speak.\n&cReason: &e%reason%\n&cExpires: &e%expiry%"
  player_kicked: "&cYou have been kicked from this server!!\n&cReason: &e%reason%"
  punishment_applied: "&aSuccessfully punished &e%player%&a&l."
  player_not_found: "&cPlayer not found or never joined the server."
  no_permission: "&cYou do not have permission to do this."
  unban_success: "&aSuccessfully unbanned &e%player%&a&l."
  unmute_success: "&aSuccessfully unmuted &e%player%&a&l."
  history_title: "&ePunishment History for &c%player%"
  help_message:
    - "&e&m-------------&r &c&lMerchPunishs Help Guide &e&m------------"
    - "&a/ban &e<player> <reason> &8- &fBans a player permanently."
    - "&a/tempban &e<player> <time> <reason> &8- &fTemp bans a player."
    - "&a/unban &e<player> &8- &fUnbans a player."
    - "&a/mute &e<player> <reason> &8- &fMutes a player permanently."
    - "&a/tempmute &e<player> <time> <reason> &8- &fTemp mutes a player."
    - "&a/unmute &e<player> &8- &fUnmutes a player."
    - "&a/ipban &e<player> <reason> &8- &fIP-bans a player."
    - "&a/kick &e<player> <reason> &8- &fKicks a player."
    - "&a/history &e<player> &8- &fShows a player's punishment history."

history_menu:
  size: 54
  fill_item:
    material: "GRAY_STAINED_GLASS_PANE"
    name: " "
  item_lore:
    - "&eType: &c%type%"
    - "&eReason: &a%reason%"
    - "&eBy: &a%staff%"
    - "&eDate: &a%date%"
    - "&eExpires: &a%expiry%"
